#!/usr/bin/env php
<?php

require_once __DIR__ . '/init.php';

use Symfony\Component\Console\CommandLoader\FactoryCommandLoader;

\Sys\Context::setConfig(new \Config\Cli());

\Sys\Context::init();

$application = new \Symfony\Component\Console\Application();

$commands = require_once ETC_PATH . '/commands.php';

$application->setCommandLoader(new FactoryCommandLoader($commands));

$application->run();
